# Script to Export All Azure Keyvault Secrets from Multiple Vaults in a single Subscription
#
# Generated by: Werner Rall
#
# Generated on: 03/11/2021
#
# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @(Az.KeyVault, Az)
#
#examples to install required Module
#Install-Module Az.KeyVault
#Import-Module Az.KeyVault -verbose -Force
#
#Parameters
Param(
[parameter(mandatory)] [string] $originSubscriptionId
)
#
#Use Connect AzAccount to connect to your azure environment or use a Connect-AzAccount -ServicePrincipal 
Connect-AzAccount
$Csv = New-Item KeyVaultExport.csv
Write-Host "KeyVaultExport File Location is in $csv" -ForegroundColor Green

#Required for one or more keyvaults?
$kvNum = Read-Host -Prompt "Is this required for 1 KeyVault [Y] or All Keyvaults [A]"
$kvNum

If($kvNum -eq "Y") 
{   $AllVaults = Read-Host -Prompt "Enter KeyVault Name"
    Write-Host "Getting Secrets for 1 Keyvault" -ForegroundColor Green
    $names = Get-AzKeyVaultSecret -VaultName $AllVaults
}
elseif ($kvNum -eq "A") {
    $AllVaults = Get-AzKeyVault -SubscriptionId $originSubscriptionId
    Write-Host "Getting All Keyvaults" -ForegroundColor Green
    
    foreach($vlt in $AllVaults)
    {
       $names = Get-AzKeyVaultSecret -VaultName $vlt.VaultName
    }
}
else
{
Write-Host "You have to Enter 'Y' or 'A'for the script to complete" -ForegroundColor Red
Break
}

Write-Host "Getting Secrets" -ForegroundColor Green
$scrtHtable = [ordered]@{}
foreach ($nme in $Names) {
    $allScrts = $nme.VaultName
    $allScrts1 = (Get-AzKeyVaultSecret -VaultName $nme.VaultName -Name $nme.Name).Name
    $allScrts2 = (Get-AzKeyVaultSecret -VaultName $nme.VaultName -Name $nme.Name -AsPlainText)
    $scrtHtable.Add("$allScrts1","$allScrts2")
}

Write-Host "Storing All secrets in CSV File" -ForegroundColor Green
$scrtHtable.GetEnumerator() |Select-Object -Property Key,Value | Export-Csv $Csv -NoTypeInformation



